# Generated by Django 5.2 on 2025-09-24 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caretaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caretaker_code", models.IntegerField()),
                ("caretaker_name", models.CharField()),
                ("caretaker_surname", models.CharField()),
                ("caretaker_cell", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resident_code", models.IntegerField()),
                ("resident_name", models.CharField()),
                ("resident_surname", models.CharField()),
                (
                    "caretaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carehome.caretaker",
                    ),
                ),
            ],
        ),
    ]
