# Generated by Django 5.2 on 2025-10-11 18:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carehome", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caretaker",
            name="id",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="caretaker",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="id",
        ),
        migrations.AddField(
            model_name="caretaker",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("DAY", "Day Shift"),
                    ("NIGHT", "Night Shift"),
                    ("BOTH", "Day & Night Shift"),
                ],
                default="DAY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="caretaker",
            name="caretaker_cell",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="caretaker",
            name="caretaker_code",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="caretaker",
            name="caretaker_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="caretaker",
            name="caretaker_surname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="resident",
            name="resident_code",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="resident",
            name="resident_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="resident",
            name="resident_surname",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Assistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("price", models.FloatField(default=0.0)),
                (
                    "caretaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carehome.caretaker",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carehome.resident",
                    ),
                ),
            ],
        ),
    ]
